// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage(errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>PWAMS Login</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"><script src=\"/static/js/vendor/htmx.min.js\"></script></head><body><div class=\"login-page\"><section class=\"login-brand\"><div class=\"brand-mark\">PWA</div><h1 style=\"margin-top:24px;\">People Welfare Association Management System</h1><p>Secure management of community welfare operations, beneficiaries, donations, aid, loans and field activities.</p><div class=\"login-features\"><div class=\"login-feature\">✓ Role-based access control</div><div class=\"login-feature\">✓ Secure session authentication</div><div class=\"login-feature\">✓ Audit-ready operations</div><div class=\"login-feature\">✓ Offline-first field support</div></div></section><section class=\"login-form-side\"><div class=\"login-card\"><h2>Welcome back</h2><p class=\"subtitle\">Sign in to your PWAMS account.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errorMsg != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"alert alert-danger\" data-auto-dismiss>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(errorMsg)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/login.templ`, Line: 31, Col: 67}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"POST\" action=\"/login\" hx-post=\"/login\" hx-target=\"body\" hx-swap=\"outerHTML\" hx-indicator=\"#login-spinner\"><div class=\"form-group\" style=\"margin-bottom:16px;\"><label class=\"form-label\" for=\"login\">Email / Username</label> <input class=\"form-control\" id=\"login\" name=\"login\" type=\"text\" autocomplete=\"username\" required></div><div class=\"form-group\" style=\"margin-bottom:18px;\"><label class=\"form-label\" for=\"password\">Password</label> <input class=\"form-control\" id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" required></div><button class=\"btn btn-primary\" style=\"width:100%;\" type=\"submit\"><span id=\"login-spinner\" class=\"htmx-indicator\" style=\"margin-right:8px;\">⏳</span> Sign In</button></form><div style=\"text-align:center;margin-top:18px;\"><a href=\"/forgot-password\" style=\"color:var(--primary);font-size:13px;font-weight:700;\">Forgot password?</a></div></div></section></div><script src=\"/static/js/app.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
